### ISSUE TITLE
Venue selection

### ISSUE THREAD

**Issue by ajs-xmr** [MoneroKon/meta#1]
| Venue            | Location        | Date               | Rooms           | Cost              | Notes              |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| [University of Neuchâtel](https://www.unine.ch)                                                 | [Neuchâtel, Switzerland](https://www.openstreetmap.org/search?query=Av.%20du%20Premier-Mars%2026%2C%202000%20Neuch%C3%A2tel%2C%20Switzerland#map=19/46.99389/6.93871)      | 30th June - 3rd July 2023 | [Aula des Jeunes-Rives](https://www.unine.ch/batiments/home/prestations/location-de-laula-des-jeunes-riv.html)  | 4,500 CHF (~4.532 EUR excl. VAT) | [LexTech Institute](https://www.lextechinstitute.ch/?lang=en) interested co-organizing some academic sessions, there is also collaboration interest from [Nym](https://nymtech.net/) and [DarkFi](https://dark.fi/), include basic A/V, Pad: https://annuel2.framapad.org/p/monerokon-neuchatel-9x2b?lang=en |
| [La Fabrika](https://www.lafabrika.cz/en/lafabrika)                                              | [Prague, Czechia](https://www.openstreetmap.org/node/2013403058)      |  23rd-26th June 2023 | two studios and large bar, catering excl. |  ~46.000 EUR excl. VAT | [Paralelni Polis](https://www.paralelnipolis.cz/o-nas/en/) interested in collaborating and Duct Tape Production (HCPP and ETH events) can help organise local production, includes 5x10m stage, 6 long tables, 12 chairs, 12 bistro tables, PA system, stage lighting, laser projector and screen (610 x 345cm) + support staff (production manager, light board operator, sound engineer, video engineer, cloakroom attendants, fireman, cleanup crew)

**Comment by monerobull** [comment]
Lucerne University of Applied Sciences and Arts taking XMR is hella based.

**Comment by rottenwheel** [comment]
Wasn't there some loose consensus on planning MoneroKon one year stateside, the following in Europe? Or viceversa; the point was to alternate between the two. If that were the case, 2023 should be held in the US, unless I am missing something.

**Comment by ajs-xmr** [comment]
@rottenstonks the idea of alternating between US/EU was talked about, but no consensus

**Comment by umma08** [comment]
@ajs-xmr can you add an estimate/approx Euro cost to the KKL Luzern costing. At current exchange rates it is coming out to €27,691.28

https://www.xe.com/currencyconverter/convert/?Amount=26760&From=CHF&To=EUR
