### ISSUE TITLE
Beverage and Food Catering

### ISSUE THREAD

**Issue by ajs-xmr** [MoneroKon/meta#26]

**Comment by michaesc** [comment]
A food truck serving HCPP in Praha is **Juicy Rare Joe**.

```
Public information:
+420 721 030 854
choose.s@seznam.cz
https://www.juicyrarejoe.cz/
```

It's one of the food trucks at HCPP that served very nice quesadillas.

**Comment by ajs-xmr** [comment]
[Dosa Dosa](https://www.happycow.net/reviews/dosa-dosa-prague-265351) - Vegan Indian/Asian
```
info@dosadosa.cz
+420 725 511 536
https://www.dosadosa.cz
```

**Comment by hundehausen** [comment]
Will there be vegan food options?

**Comment by ajs-xmr** [comment]
@hundehausen yes, we will have vegan options for food trucks and the speaker's dinner

**Comment by hundehausen** [comment]
That's awesome. Thank you.
