### ISSUE TITLE
Swag

### ISSUE THREAD

**Issue by ajs-xmr** [MoneroKon/meta#5]

**Comment by monerobull** [comment]
Should [this](https://github.com/MoneroKon/meta/issues/4#issuecomment-1245435411) work out, I'd bring the stickers available on monerosupplies.com with me to hand out :)

**Comment by michaesc** [comment]
This is a high risk task if we decide to distribute good quality merchandise again. The attempted three month production duration was not enough, and caused people to have complaints like some parts being manufactured outside of the area.

I'm not sure how to place this Kanban card early in developments, like four to five months.

**Comment by ajs-xmr** [comment]
Local/EU-based merch suppliers should be preferred

**Comment by monerobull** [comment]
Am based in Germany, Ive checked and driving to switzerland locations would take about double than flight but I could get most of the merch and bring it with me.

**Comment by michaesc** [comment]
> Local/EU-based merch suppliers should be preferred
>
Visitors expressed just the opposite, that high quality merchandise suppliers are preferred.

**Comment by monerobull** [comment]
I am currently working on a Monerochan plushy. The current plan is to have 100 made to sell for my own monerosupplies.com but if we want some for swag i could order more and provide them to the monerokon swag bucket at cost (should be about 18-20$)
